### ISSUE TITLE
Rover Pro /robot_status msg battery info fields missing

### ISSUE THREAD

**Issue by TobyUllrich** [RoverRobotics/librover#16]
When using the pro.launch on our rover pro the /robot_status topics is missing many fields and some seem to be wrong

```
layout:
  dim: []
  data_offset: 0
data: [0.0, -860.0, 7.0, 102.0, 0.0, 0.0, -756.0, 16.0, 255.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 64637.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```

This is a message during driving backwards. The two drive motor information seems plausible but the battery information seems wrong as the robot was not charging during this and there is no Battery Voltage displayed.

When requesting the robot information on the /robot_unique_info topic the response is the following

```
layout: 
  dim: []
  data_offset: 0
data: [0.0, 10008.0, 0.0, 0.0, 0.0]
```

This rover pro unite was flashed with the supplied firmware flasher before these events.

**Comment by TobyUllrich** [comment]
I followed your steps and the robot status is now filled with data, but some of the data fields seem to be off the possible values found [here](https://roverrobotics.com/blogs/news/uart-protocol). 
```
layout:
  dim: []
  data_offset: 0
data: [1.0, 0.0, 24.0, 102.0, 0.0, 2.0, 0.0, 42.0, 255.0, 0.0, 3.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 642.0, 0.0, 0.0, 570.0, 24.0, 255.0, 91.0, 0.0, 0.0, 165.0, 642.0, 570.0]
```
Especially the first value of 642, which represents BATTERY_VOLTAGE_B, and 255 which represents the REG_ROBOT_REL_SOC_A. Basically, the Battery information is now there but the values seem wrong.

Here are the changes I made to librover to accommodate the needed information fields [changes.txt](https://github.com/RoverRobotics/librover/files/6988169/250e62d425a08e59e71f944a4922c1b7ecaeac03.txt)
